'use client';

import React, { useState } from 'react';
import { HelpCircle, ChevronDown, ChevronUp, ShieldCheck, DollarSign, Database, Activity, Sparkles, Lock } from 'lucide-react';

interface FAQItem {
  question: string;
  icon: React.ComponentType<{ className?: string }>;
  answer: React.ReactNode;
}

export function FAQSection() {
  const [openIdx, setOpenIdx] = useState<number | null>(0); // First item open by default

  const toggleFAQ = (idx: number) => {
    setOpenIdx(openIdx === idx ? null : idx);
  };

  const faqs: FAQItem[] = [
    {
      question: 'Is PocketETF safe and non-custodial?',
      icon: ShieldCheck,
      answer: (
        <div className="space-y-2">
          <p>
            <strong>Yes, 100%.</strong> PocketETF is a completely non-custodial execution engine. We never hold your funds, manage user accounts, or ask for private keys.
          </p>
          <p className="text-slate-400">
            Every transaction is compiled directly in your browser or through the verified Solana Actions API into an atomic <strong>VersionedTransaction (v0)</strong>. Your wallet (Phantom, Solflare, Backpack) signs swaps directly with decentralized liquidity pools (Whirlpool, Meteora, Raydium) routed through Jupiter. If any swap fails or experiences slippage, the entire transaction reverts automatically—zero funds are ever stranded.
          </p>
        </div>
      ),
    },
    {
      question: 'Where do the tokenized stocks and assets come from?',
      icon: Database,
      answer: (
        <div className="space-y-2">
          <p>
            All equity assets in the PocketETF catalog are <strong>canonical tokenized stocks</strong> issued and custodied by regulated entities like <strong>Backpack Securities</strong>, coordinated via the <strong>Sunrise</strong> liquidity layer on Solana, and supported by Ondo and Dinari.
          </p>
          <p className="text-slate-400">
            Each token represents 1:1 backing by actual physical shares held in licensed US custodian brokerages. These shares are traded 24/7 on decentralized Automated Market Makers (Whirlpool, Meteora, Raydium) and can be redeemed for the underlying securities. PocketETF acts as the consumer ETF layer, bundling these individual tokenized shares into diversified portfolios.
          </p>
        </div>
      ),
    },
    {
      question: 'Is this a free platform, or does it generate revenue and how?',
      icon: DollarSign,
      answer: (
        <div className="space-y-2">
          <p>
            <strong>Zero Fees During Hackathon Alpha:</strong> PocketETF charges <strong>0% protocol fees</strong> during our initial alpha launch. 100% of your USDC is deployed directly into your chosen equity allocation.
          </p>
          <p className="text-slate-400">
            <strong>Production Revenue Model:</strong> In production, PocketETF activates an ultra-low <strong>10–15 bps (0.10%–0.15%)</strong> Jupiter platform routing fee. For every $100 ETF invested, just $0.15 USDC is routed to the protocol treasury in the exact same atomic transaction—with zero extra gas or transaction size. 
          </p>
          <p className="text-slate-400">
            <strong>Creator Revenue Share:</strong> Curators who assemble custom ETFs in the Creator Studio earn an automated <strong>50% split</strong> of the routing fee on all volume generated by their shared Blinks on Twitter/X, creating a viral distribution incentive.
          </p>
        </div>
      ),
    },
    {
      question: 'How does Pyth Network power the pricing and Net Asset Value (NAV)?',
      icon: Activity,
      answer: (
        <div className="space-y-2">
          <p>
            PocketETF integrates <strong>Pyth Network Hermes v2</strong> real-time price feeds for all US equities (NVDA, AAPL, MSFT, TSLA, SPY, QQQ) and crypto assets.
          </p>
          <p className="text-slate-400">
            Unlike simple spot AMM trackers, PocketETF dynamically computes the true institutional <strong>Net Asset Value (NAV)</strong> of each ETF basket: <code className="text-[#00D69F] font-mono">NAV = Σ(Pyth Price_i × Weight_i)</code>. Pyth also provides institutional <strong>Confidence Intervals (±σ)</strong>, showing investors the exact spread before executing their swap on Jupiter.
          </p>
        </div>
      ),
    },
    {
      question: 'What happens if I don’t have enough Solana USDC in my wallet?',
      icon: Lock,
      answer: (
        <div className="space-y-2">
          <p>
            PocketETF features an automated <strong>Zero-Gas Pre-Flight Wallet Guardrail</strong>. Before any transaction is generated, our API verifies your on-chain USDC Associated Token Account balance.
          </p>
          <p className="text-slate-400">
            If your wallet does not hold enough USDC for your selected preset ($5, $10, $25, $50, $100), the system displays a clear warning notice and stops immediately. Phantom and Solflare will <strong>never open a transaction prompt</strong>, preventing you from clicking &quot;confirm anyway&quot; and saving your SOL network gas fees.
          </p>
        </div>
      ),
    },
    {
      question: 'Can I sell, rebalance, or withdraw my stocks anytime?',
      icon: Sparkles,
      answer: (
        <div className="space-y-2">
          <p>
            <strong>Yes, you have full ownership.</strong> When you execute a PocketETF basket, the individual SPL tokens settle directly into your self-custody wallet (Phantom, Solflare, Backpack).
          </p>
          <p className="text-slate-400">
            You are not locked into any proprietary vault or platform. You can hold them forever with 0% annual management fees, sell individual stocks on Jupiter or Raydium anytime, or use PocketETF’s 1-click unwind flow to convert your basket back to USDC.
          </p>
        </div>
      ),
    },
  ];

  return (
    <section id="faq" className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16 scroll-mt-20">
      <div className="text-center mb-12">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#146EF5]/10 border border-[#146EF5]/30 text-xs font-mono text-[#00D69F] mb-4">
          <HelpCircle className="w-3.5 h-3.5 text-[#00D69F]" />
          <span>Frequently Asked Questions</span>
        </div>
        <h2 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
          Everything You Need to Know
        </h2>
        <p className="text-sm text-slate-400 mt-3 leading-relaxed">
          Transparent answers regarding safety, real-world asset provenance, Pyth oracles, and protocol fees.
        </p>
      </div>

      <div className="space-y-3">
        {faqs.map((faq, idx) => {
          const isOpen = openIdx === idx;
          const Icon = faq.icon;

          return (
            <div
              key={idx}
              className={`rounded-2xl border transition-all duration-200 overflow-hidden ${
                isOpen
                  ? 'bg-[#0A1128]/90 border-[#146EF5]/50 shadow-lg shadow-blue-500/10'
                  : 'bg-white/[0.02] border-white/[0.06] hover:border-white/20'
              }`}
            >
              <button
                type="button"
                onClick={() => toggleFAQ(idx)}
                className="w-full py-4 px-5 flex items-center justify-between text-left gap-4"
              >
                <div className="flex items-center gap-3">
                  <div
                    className={`w-8 h-8 rounded-xl flex items-center justify-center shrink-0 transition-colors ${
                      isOpen
                        ? 'bg-[#146EF5]/20 text-[#00D69F] border border-[#146EF5]/40'
                        : 'bg-white/[0.04] text-slate-400 border border-white/10'
                    }`}
                  >
                    <Icon className="w-4 h-4" />
                  </div>
                  <span className="text-sm sm:text-base font-bold text-white">
                    {faq.question}
                  </span>
                </div>

                <div className="text-slate-400 shrink-0">
                  {isOpen ? <ChevronUp className="w-4 h-4 text-[#00D69F]" /> : <ChevronDown className="w-4 h-4" />}
                </div>
              </button>

              {isOpen && (
                <div className="px-5 pb-5 pt-1 text-xs sm:text-sm text-slate-300 leading-relaxed border-t border-white/[0.05] animate-fadeIn">
                  {faq.answer}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </section>
  );
}
